services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    networks:
      - backend
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - PORT=${PORT}
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - ${PORT}:${PORT}
    volumes:
      - /usr/src/app/node_modules
      - ./src:/usr/src/app/src
  postgres:
    build:
      context: ./src/database
      dockerfile: Dockerfile
    networks:
      - backend
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    restart: always
    volumes:
      - PGDATA:/var/lib/postgresql/data
volumes:
  PGDATA:
networks:
  backend:
    driver: bridge
